#Hyprpaper
wallpaper { #Samsung
    monitor = DP-3
    path = /home/ivy/Pictures/Wallpaper/01.jpg
    fit_mode = cover
}

wallpaper { #Acer
    monitor = DP-1
    path = /home/ivy/Pictures/Wallpaper/06.jpg
    fit_mode = cover
}

wallpaper { #Huion
    monitor = HDMI-A-1
    path = /home/ivy/Pictures/Wallpaper/03.jpg
    fit_mode = cover
}

wallpaper { #fallback
    monitor = 
    path = /home/ivy/Pictures/Wallpaper/03.jpg
    fit_mode = cover
}
